### ISSUE TITLE
Autonomous mode does not seem to update Pose X or Y correctly 

### ISSUE THREAD

**Issue by martygubow** [HuskieRobotics/3061-lib#25]
My Teleoperate mode seems to work fine.  Pose X, Y seem to be updating correctly.   When I run in autonomous the Pose values seem to update much slower/less .  This causes the control loop to increase the velocity much higher than the max level.  I have it set to 1m/s but it is going ~10m/s sec because the Pose update is a fraction of what it should be.  This could be operator error? I am new to this lib and to pathplanner.  I also tried to create a very simple testpath.path  (move robot 1m straight line) . I notice when the wheels are spinning very fast in Autonomous the Pose X,Y are update very little.   Could it be a scaling issue?  I am running MK4 L2, with Falcon 500 , cancoders.  Navx2 gyro.  The robot is on a cart while testing.   Thank you for publishing this lib!

**Comment by martygubow** [comment]
It appears the Pose Y distance calculation is opposite of the motor encoder.  I tried flipping the SwerveModuleConstants but it does not appear to help.   I will need to keep looking at this.   Any suggestions would be appreciated.  I think it is a setup error.

**Comment by gcschmit** [comment]
Are you able to share a link to your GitHub? Also, if you can share the wpilog file from the simple test path, that would be very useful.

If the motor encoder was out of phase with the motor, that would impact the pose estimation in both teleop and auto. It is strange that pose estimation works in one mode and not the other since there is little different about those two code paths....

**Comment by martygubow** [comment]
Thank you for your help!    This is the link to my repository.  https://github.com/FRC7224/FRC2023B
With some configuration I think the orientation is correct.  When the robot moves forward, I get a positive x?  I am still having trouble. with  PathPlanner.   I do not think it is creating the trajectory file correctly. I tried to create a very simple path with testpaths1 and it causes the roborio to crash.  testpaths8 (original) is in the code so it runs.   When I run autonomous it goes open loop and way to fast.  Most of these tools are new to me Advantagescope and  Pathplanner.   Any help would be appreciated!!

**Comment by gcschmit** [comment]
The Navx may report clockwise as the positive direction when installed in a roboRIO "facing up". If so, that will need to be inverted as the code expects counter clockwise as the positive direction.

**Comment by martygubow** [comment]
Geoff,

Yes, I just noticed that this morning. (Thank  you)  But I don't think this
would cause the path software to go open loop.   I am trying to move in a
straight line 1m.  (keep it simple to start)

Marty

**Comment by gcschmit** [comment]
I agree about the NavX, hopefully, the previous suggestions will help address the autonomous issue.

**Comment by martygubow** [comment]
Thank you for your suggestions! I believe I have the orientation correct now.   I am still having velocity issues in autonomous mode.  I have the AUTO_MAX_SPEED_METERS_PER_SECOND set to 1.0 and I also set it to 1.0 in the path file.   But I am seeing 4.5  m/s.   (note: I have the robot on a cart )

**Comment by gcschmit** [comment]
Would you send me the log file where you see this behavior? I can replay it in AdvantageScope against your code in GitHub and have a better sense of what is going on.

**Comment by martygubow** [comment]
I have not been able to get the file saving to work.   I get an error
failed to open media/sda1
Does the flash drive need to be formatted any special way?

I exported from advantage scope program  and the file is attached.

Thank you!

**Comment by gcschmit** [comment]
I don't think attachments work when responding to GitHub issues. Would you add the file to your GitHub and let me know which file to look at and which branch (if not main) to replay with?

**Comment by gcschmit** [comment]
Did you resolve the issue? Assuming so, what was the issue in case others experience similar problems.

**Comment by martygubow** [comment]
[7224test2.zip](https://github.com/HuskieRobotics/3061-lib/files/10528282/7224test2.zip)

**Comment by martygubow** [comment]
Note: had to zip it for git to take it

Yes, your directions were helpful.  I swapped some signs and setup values in the swerve constants in order to get the orientation correct.

**Comment by gcschmit** [comment]
A potential insight, a tip, and a question.

I think the log file that you sent for testPaths8 drove the wheels at full speed because the robot was on a cart and wasn't able to rotate. The AUTO_MAX_SPEED_METERS_PER_SECOND constant impacts the path that is generated, but it doesn't limit the PID controllers used to try and keep the robot on the auto path. Since the robot is on a cart and cannot rotate, the angle reported by the gyro and the angle specified in the path end up way off. Therefore, the PID controller for the auto path tries to make the robot turn faster by increasing the wheel speeds well beyond 1 m/s. I expect that if you run the testPaths1 copy auto path, the robot will drive at the expected speed on the cart. In addition, now that the geometry is consistent, running the auto paths with the robot on the ground should behave as expected.

I believe the flash drive for logging is just formatted as FAT32. I will have to check at school to verify. If you are using a roboRIO 2, I believe the path is /media/sda1 if the flash drive is in the port closer to the edge of the roboRIO. You can insert the flash drive, [ftp into the roboRIO](https://docs.wpilib.org/en/latest/docs/software/roborio-info/roborio-ftp.html), and list the contents of the media directory to see where it was mounted.

Just to confirm since you closed this issue. Is everything working as expected now?

**Comment by martygubow** [comment]
Thanks this helps!   I will try to create  a path that has the robot driving straight.  This way we will not have any gyro error.  I would like to get the autonomous working more controlled before I take it off the cart.    I can move it to a more open space at the school Monday to try it.   In past year I have had robots drive into the wall.  They can accelerate faster than my space bar reaction. I am running a  roborio 1.0.  I did get it to save a file ones.  A second time it seemed to corrupt the flash drive.  I did not attend to close the issue but it ok.  The initial issue  is resolved.   The Pose values are correct. The information you gave on making sure the configuration  is correct was helpful. You may want to add it to the readme.Marty GubowOn Jan 28, 2023, at 6:36 PM, Geoff Schmit ***@***.***> wrote:﻿
A potential insight, a tip, and a question.
I think the log file that you sent for testPaths8 drove the wheels at full speed because the robot was on a cart and wasn't able to rotate. The AUTO_MAX_SPEED_METERS_PER_SECOND constant impacts the path that is generated, but it doesn't limit the PID controllers used to try and keep the robot on the auto path. Since the robot is on a cart and cannot rotate, the angle reported by the gyro and the angle specified in the path end up way off. Therefore, the PID controller for the auto path tries to make the robot turn faster by increasing the wheel speeds well beyond 1 m/s. I expect that if you run the testPaths1 copy auto path, the robot will drive at the expected speed on the cart. In addition, now that the geometry is consistent, running the auto paths with the robot on the ground should behave as expected.
I believe the flash drive for logging is just formatted as FAT32. I will have to check at school to verify. If you are using a roboRIO 2, I believe the path is /media/sda1 if the flash drive is in the port closer to the edge of the roboRIO. You can insert the flash drive, ftp into the roboRIO, and list the contents of the media directory to see where it was mounted.
Just to confirm since you closed this issue. Is everything working as expected now?
